server:
  port: 8083

spring:
  application:
    name: template-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/bank_notifications
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      timeout: 5000ms
      connect-timeout: 5000ms
      lettuce:
        pool:
          enabled: true            # 显式开启连接池
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms

internal:
  api:
    token: ${INTERNAL_API_TOKEN:ZGV2LWludGVybmFsLWFwaS10b2tlbi0yMDI2}